// About page
import { client } from "@/prismicio";
import { SliceZone } from "@prismicio/react";
import { components } from "@/slices"; // This is auto-generated by Slice Machine
export default async function AboutPage() {
  const about = await client.getSingle("about");

  return (
    <main>
      <SliceZone slices={about.data.slices} components={components} />
    </main>
  );
}
