// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  blog_post: dynamic(() => import("./BlogPost")),
  call_to_action: dynamic(() => import("./CallToAction")),
  headline_media_description_cta: dynamic(
    () => import("./HeadlineMediaDescriptionCta"),
  ),
  hero: dynamic(() => import("./Hero")),
  landing_page: dynamic(() => import("./LandingPage")),
};
